# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-18 11:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribers',
            old_name='nme',
            new_name='name',
        ),
    ]
